### ISSUE TITLE
A little question about the code.

### ISSUE THREAD

**Issue by RoyalVane** [Gaoyiminggithub/Graphonomy#11]
Thanks for sharing such excellent work! I find the code here looks wired because the source_graph_con3 is never used in the function. I guess that it is a mistake maybe?  https://github.com/Gaoyiminggithub/Graphonomy/blob/5e80aa8d09100998a6e8a4b481cbb44f358a2c6a/networks/deeplab_xception_transfer.py#L778

**Comment by Gaoyiminggithub** [comment]
Hi, thanks for your attention, it is used in [here](https://github.com/Gaoyiminggithub/Graphonomy/blob/5e80aa8d09100998a6e8a4b481cbb44f358a2c6a/networks/deeplab_xception_transfer.py#L802)

**Comment by RoyalVane** [comment]
Thank you for your reply. Here I mean that the convolution function "source_graph3 = self.source_graph_**conv2**" should be the "source_graph3 = self.source_graph_**conv3**", maybe?

**Comment by Gaoyiminggithub** [comment]
Hi, thank you for your reply!
Yes, it should be the "source_graph3 = self.source_graph_conv3".
And I will fix it later.

**Comment by Gaoyiminggithub** [comment]
I have fixed it.
Thanks for your helpful issue.
