### ISSUE TITLE
I can not find ATR and CIHP test datasets.  

### ISSUE THREAD

**Issue by odefiao** [Gaoyiminggithub/Graphonomy#12]
I can not find ATR and CIHP test datasets.  I want to know how you tested on these two datasets.
Besides，How to Train Deeplabv3+ on human parsing datasets. Thank you!!!

**Comment by Gaoyiminggithub** [comment]
Hi, thank you for your attention.
Are there the test datasets of CIHP and ATR in the dataset download link in Readme.md ?
The test script will be released ASAP. You could change the test script of Pascal to test these two datasets.
Q: How to Train Deeplabv3+ on human parsing datasets
A: You just need to change the network in [here](https://github.com/Gaoyiminggithub/Graphonomy/blob/master/exp/transfer/train_cihp_from_pascal.py#L179) to the deeplabV3+ model which in [here](https://github.com/Gaoyiminggithub/Graphonomy/blob/master/networks/deeplab_xception.py#L394). And then you change [lline](https://github.com/Gaoyiminggithub/Graphonomy/blob/master/exp/transfer/train_cihp_from_pascal.py#L275) `outputs = net.forward(inputs, adj1, adj3, adj2)` -> `outputs = net.forward(inputs)`. Lastly, remembering to load the pre-trained model.
