### ISSUE TITLE
CUDA memory problem

### ISSUE THREAD

**Issue by vincentwei0919** [Gaoyiminggithub/Graphonomy#19]
hi, great work！
currently I try to use your inference model to predict my data. But when I use universal_trained.pth as the pretrained model with gpu memory 12GB, it always report error meaning not enough cuda memory. so I wonder how much memory does the model need? any ideas to optimize this? should I use small resized pictures or any other things I could do?
waiting for your reply, thanks!

**Comment by tasinislam21** [comment]
You need to reduce the image resolution. Ideally, the overall size of the image should be less than 50kb.
