### ISSUE TITLE
How to fine-tune this model for a semantic segmentation task for human parsing ?

### ISSUE THREAD

**Issue by rishab-sharma** [Gaoyiminggithub/Graphonomy#20]
Can this model be mapped to a single node graph for human parsing ( Semantic Segmentation - 2 classes - human / Background), if yes, how should I calculate the adj matrix for the same. Any help or guidance on the same would be appreciated.

**Comment by Ahanio** [comment]
Did you figure it out?

**Comment by Gaoyiminggithub** [comment]
You can set the label to 2 classes - human/ Background, and then train the model. However, our method may not show the superiority with 2 classes only.
