### ISSUE TITLE
why actual performance is worse than deeplab v3+?

### ISSUE THREAD

**Issue by plmsmile** [Gaoyiminggithub/Graphonomy#21]
I find some cases show its worse than deeplab v3+.

# BadCase
## raw image
![image](https://user-images.githubusercontent.com/17981649/70911552-18458000-204d-11ea-9680-0a8ccec3fbb6.png)

## graphonomy
the model is download from your release:[CIHP pretrained model download link](https://drive.google.com/file/d/1eUe18HoH05p0yFUd_sN6GXdTj82aW0m9/view?usp=sharing)
![image](https://user-images.githubusercontent.com/17981649/70911577-28f5f600-204d-11ea-97f6-d71c8c6139cf.png)

## deeplab v3+
![image](https://user-images.githubusercontent.com/17981649/70911621-38753f00-204d-11ea-9a07-7941a0dd4356.png)

# Potential reasons
I guess maybe i have downloaded a wrong model or something wrong, but i cannot figure it out. Thank you for your share and read this issue.

**Comment by plmsmile** [comment]
After i downloaded the universal model, the performance is quite good! Good work, thanks for share!

**Comment by dragen1860** [comment]
@plmsmile hi, I  wonder how to run the pure deeplabv3 experiment. Do you run pure deeplabv3 experient using the repo code? Could you give some tips on how to run? Thank you.
