### ISSUE TITLE
How to train and evaluate on deeplabv3 baseline?

### ISSUE THREAD

**Issue by dragen1860** [Gaoyiminggithub/Graphonomy#22]
Dear author, 
  Thanks for your neat implementation.
   I found the report deeplabv3 performance in this paper is relatively close to Graphonomy. Therefore I want to reproduce the deeplabv3 related experirments. Could you kindly give some tips on how to train and evaluate on deeplabv3 baselines using your repo.? Thank you.

**Comment by Gaoyiminggithub** [comment]
Hi,
sorry for the late response.
You can use the class in deeplab_xception.py to train the deeplabv3.

**Comment by Gaoyiminggithub** [comment]
Close due to long time no reply.
