### ISSUE TITLE
How to distinguish instances

### ISSUE THREAD

**Issue by JonathanLehner** [Gaoyiminggithub/Graphonomy#3]
How can we get the instances?
If there are two humans in the image, can we get a list of the areas that belong to each of them?

**Comment by Gaoyiminggithub** [comment]
Hi, 
If you want to get the pred of instances, you can get the instances by using the pretrained Mask-rcnn to detect the instance human mask.

**Comment by JonathanLehner** [comment]
great, thank you! I will try it

**Comment by JonathanLehner** [comment]
where is the model?

**Comment by Gaoyiminggithub** [comment]
You can get the pretrained Mask-rcnn model in [here](https://github.com/facebookresearch/maskrcnn-benchmark). ( I have used this pretrained model to get the instance mask, and then combined with our parsing results that we could get the stoa performance of instance human parsing.)

**Comment by JonathanLehner** [comment]
Thanks! how did you combine the results?

**Comment by Gaoyiminggithub** [comment]
We use the instance person mask to detect the instance part of the human part. (e.g., we have a human instance mask and a semantic segmentation, we use the instance person mask to detect the person part that belongs to which instance human.)
