### ISSUE TITLE
How to compute the matrix of cihp2pascal_nlp_adj?

### ISSUE THREAD

**Issue by YOKE** [Gaoyiminggithub/Graphonomy#4]
![image](https://user-images.githubusercontent.com/34132063/57532941-34729780-736f-11e9-96bb-c406aa664e10.png)
In your paper, I don't know how to get the value of v for a node. 
Can you explain it in detail for me? Really grateful!

**Comment by Gaoyiminggithub** [comment]
Hi, the v is a word embedding vector. We use the [glove](https://nlp.stanford.edu/projects/glove/) to get the word embedding of each human part. For example, the value v of the node of 'head' is the word embedding of the 'head'.
