### ISSUE TITLE
Why the speed is much slow than SSL

### ISSUE THREAD

**Issue by wugh** [Gaoyiminggithub/Graphonomy#5]
Hi, Gaoyiminggithub 

I'm look for a good human semantic parser recently I found serval projects.

* one is your one,
* another is [SSL](https://github.com/Engineering-Course/LIP_SSL)

Because the `LIP_SSL` didn't annotated the neck part of human, but your code can handle this.
But why the speed of Graphonomy is much more slower than `LIP_SSL`, is there anyway I can speed up.

**Comment by Gaoyiminggithub** [comment]
Hi, 
There may be two reasons for that: 1. SSL tests only use one scale while we use 7 scales. You can change the scale list to [1] in  [here](https://github.com/Gaoyiminggithub/Graphonomy/blob/master/exp/inference/inference.py#L110) to speed up. 2. SSL uses the framework of Caffe which may be faster than Pytorch.

**Comment by wugh** [comment]
Thanks,
I will try the scale first, I also see some related section in your paper.
But there is no related experiments to evaluate the performance if we inference without multi scale.

**Comment by Gaoyiminggithub** [comment]
Hi,
the reason why there are no experiments without multi-scale is that previous work reported the results with multi-scale.
