### ISSUE TITLE
How to train on a custom dataset

### ISSUE THREAD

**Issue by kshitijqwerty** [Gaoyiminggithub/Graphonomy#6]
I need some information on training on my custom dataset with 2 labels - for human and background. Thanks

**Comment by Gaoyiminggithub** [comment]
Hi,
I think maybe you can just use Deeplab to do it. You can refer to the [Deeplab](https://github.com/tensorflow/models/tree/master/research/deeplab) which may be good enough on your custom dataset.

**Comment by kshitijqwerty** [comment]
Thanks, I just need to know how can I include watches and belts as its classifying it as background.
Does this segment human before classifying it further to other classes?
![53](https://user-images.githubusercontent.com/16077478/58017192-30880780-7b1d-11e9-8d62-73dd007dce2f.jpg)

**Comment by Gaoyiminggithub** [comment]
Hi，
1. You need to train/fine-tune the model with the label of watches and belts.
2. Our model does not segment human. You can use Deeplab or add a branch to segment human. It is also needed to train/fine-tune the model. Maybe you can try to use the results of the person-part segment to segment human.

**Comment by kshitijqwerty** [comment]
Ok, I found one dataset for my needs 
[MHP v2](https://github.com/ZhaoJ9014/Multi-Human-Parsing)
So i have formatted the data like CIHP
1) it has 59 classes so would it be a problem if I train it on transfer learning and how to correctly load it
2) I am getting 1 channel error but my images are 3 channel rgb
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])
Thanks

**Comment by Gaoyiminggithub** [comment]
Hi,
1. For quickly train on it, you can change the `n_classes' to 59 in the [here](https://github.com/Gaoyiminggithub/Graphonomy/blob/master/networks/deeplab_xception.py#L438).
2. Can you give me more information about the ValueError? Thanks.
